on:
  push:

jobs:
  deploy:
    name: "Deploy v4000 Docs on Cloudflare Workers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
      - name: Checkout submodule to v4000
        run: |
          cd kaplay
          git fetch --tags
          TAG=$(git tag --list '4000*' --sort=-v:refname creatordate | head -n 1)
          echo $TAG
          git checkout $TAG
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_KEY }}
          command: pages deploy dist --project-name=kaplay4000
          preCommands: "pnpm i && pnpm build"

  deploylegacy:
    name: "Deploy v3001 Docs on Cloudflare Workers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
      - name: Checkout submodule to v3001
        run: |
          cd kaplay
          git fetch --tags
          TAG2=$(git tag --list '3001.0*' --sort=-v:refname creatordate | head -n 1)
          echo $TAG2
          git checkout $TAG2
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_KEY }}
          command: pages deploy dist --project-name=kaplay3001
          preCommands: "pnpm i && pnpm build"
