on:
  push:

jobs:
  deploy:
    name: "Deploy v4000 Docs on Cloudflare Workers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
      - name: Get latest tag
        uses: rexdefuror/get-latest-tag@v1.0.1
        with:
              token: ${{ secrets.GITHUB_TOKEN }}
              owner: ${{ github.repository_owner }}
              repo: "kaplayjs/kaplay"
              prefix: 4000 # optional
              suffix: '' # optional
              regex: '' # optional
              releaseOnly: true # optional
      - name: Checkout submodule to v4000
        run: |
          cd kaplay
          git fetch --tags 
          git checkout ${{ env.LATEST_TAG }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_KEY }}
          command: pages deploy dist --project-name=kaplay4000
          preCommands: "pnpm i && pnpm build"

  deploylegacy:
    name: "Deploy v3001 Docs on Cloudflare Workers"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-tags: true
      - name: Get Latest Tag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          prefix: 3000
      - name: Checkout submodule to v3001
        run: |
          cd kaplay
          git fetch --tags 
          git checkout ${{ steps.previoustag.outputs.tag }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_KEY }}
          command: pages deploy dist --project-name=kaplay3001
          preCommands: "pnpm i && pnpm build"
